-- ============================================================
-- Control Tower v3.0 — Migraciones SQL
-- Ejecutar en el SQL Editor del dashboard de Supabase
-- ============================================================

-- ─── 1. Tabla admin_actions_log ──────────────────────────────
create table if not exists public.admin_actions_log (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  admin_email text not null,
  action      text not null,   -- 'force_pro', 'block_user', 'delete_user', 'delete_moment', 'send_push', etc.
  target_id   text,            -- user_id, moment_id, etc.
  metadata    jsonb            -- { "plan": "pro", "reason": "soporte", "active": true }
);

alter table public.admin_actions_log enable row level security;

drop policy if exists "Admin only" on public.admin_actions_log;
create policy "Admin only" on public.admin_actions_log
  for all
  using (public.is_admin())
  with check (public.is_admin());


-- ─── 2. RPC admin_force_pro ──────────────────────────────────
create or replace function public.admin_force_pro(
  p_target_user_id uuid,
  p_active         boolean
)
returns void
language plpgsql
security definer
as $$
begin
  if not public.is_admin() then
    raise exception 'Unauthorized: admin access required';
  end if;

  update public.profiles
  set
    plan           = case when p_active then 'pro' else 'free' end,
    pro_expires_at = null
  where id = p_target_user_id;

  if not found then
    raise exception 'User profile not found for id %', p_target_user_id;
  end if;
end;
$$;


-- ─── 3. RPC get_admin_users_v2 ───────────────────────────────
-- Extiende get_admin_users() con plan, total_habits y last_close.
-- No reemplaza la existente (compatibilidad hacia atrás).
create or replace function public.get_admin_users_v2()
returns table (
  user_id       uuid,
  email         text,
  created_at    timestamptz,
  is_blocked    boolean,
  last_seen     timestamptz,
  plan          text,
  total_habits  bigint,
  last_close    timestamptz
)
language sql
security definer
as $$
  select
    up.user_id,
    up.email,
    up.created_at,
    up.is_blocked,
    up.last_seen,
    coalesce(p.plan, 'free')   as plan,
    count(distinct h.id)        as total_habits,
    max(dl.created_at)          as last_close
  from public.user_profiles up
  left join public.profiles   p  on p.id        = up.user_id
  left join public.habits     h  on h.user_id   = up.user_id
  left join public.daily_logs dl on dl.user_id  = up.user_id
                                 and dl.status   = 'summary'
  group by
    up.user_id,
    up.email,
    up.created_at,
    up.is_blocked,
    up.last_seen,
    p.plan
  order by up.created_at desc;
$$;


-- ─── 4. Soft-delete en shared_moments ────────────────────────
alter table public.shared_moments
  add column if not exists is_deleted boolean default false;

-- Actualizar el índice de consulta frecuente (opcional pero recomendado)
create index if not exists shared_moments_not_deleted_idx
  on public.shared_moments (created_at desc)
  where is_deleted = false;
